[package]
name = "xmoney_role"
edition = "2024.beta"
published-at = "0xe0917b74a5912e4ad186ac634e29c922ab83903f71af7500969f9411706f9b9a"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.57.2", override = true }
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "mainnet-v1.57.2", override = true }

[addresses]
xmoney_role = "0xe0917b74a5912e4ad186ac634e29c922ab83903f71af7500969f9411706f9b9a"
